root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /sad
        permanent: true

sad:
    resource: "@SADBundle/Controller/"
    type:     annotation
    prefix:   /sad
    
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

chamada:
    resource: "@SADBundle/Controller/ChamadaController.php"
    type:     annotation
    prefix:   /chamada

