parameters:
    dao.class.candidato:  SerBinario\SAD\Bundle\SADBundle\DAO\CandidatoDAO
    dao.class.autonomo:  SerBinario\SAD\Bundle\SADBundle\DAO\AutonomoDAO
    dao.class.empreendedor: SerBinario\SAD\Bundle\SADBundle\DAO\EmpreendedorDAO
    dao.class.empresa: SerBinario\SAD\Bundle\SADBundle\DAO\EmpresaDAO
    dao.class.curso: SerBinario\SAD\Bundle\SADBundle\DAO\CursoDAO
    dao.class.capacitacoes: SerBinario\SAD\Bundle\SADBundle\DAO\CapacitacoesDAO
    dao.class.empresaCurso: SerBinario\SAD\Bundle\SADBundle\DAO\EmpresaCursoDAO
    dao.class.empresaCapacitacoes: SerBinario\SAD\Bundle\SADBundle\DAO\EmpresaCapacitacoesDAO
    dao.class.vagas: SerBinario\SAD\Bundle\SADBundle\DAO\VagaDAO
    dao.class.vagaDisponivel: SerBinario\SAD\Bundle\SADBundle\DAO\VagaDisponivelDAO
    dao.class.areaDesejadaDAO: SerBinario\SAD\Bundle\SADBundle\DAO\AreaDesejadaDAO
    dao.class.funcaoDAO: SerBinario\SAD\Bundle\SADBundle\DAO\FuncaoDAO
    dao.class.chamadaDAO: SerBinario\SAD\Bundle\SADBundle\DAO\ChamadaDAO
    rn.class.autonomo:   SerBinario\SAD\Bundle\SADBundle\RN\AutonomoRN
    rn.class.candidato:   SerBinario\SAD\Bundle\SADBundle\RN\CandidatoRN
    rn.class.empreendedor: SerBinario\SAD\Bundle\SADBundle\RN\EmpreendedorRN
    rn.class.empresa: SerBinario\SAD\Bundle\SADBundle\RN\EmpresaRN
    rn.class.curso: SerBinario\SAD\Bundle\SADBundle\RN\CursosRN
    rn.class.capacitacoes: SerBinario\SAD\Bundle\SADBundle\RN\CapacitacoesRN
    rn.class.empresaCurso: SerBinario\SAD\Bundle\SADBundle\RN\EmpresaCursosRN
    rn.class.empresaCapacitacoes: SerBinario\SAD\Bundle\SADBundle\RN\EmpresaCapacitacoesRN
    rn.class.vagas: SerBinario\SAD\Bundle\SADBundle\RN\VagaRN
    rn.class.vagaDisponivel: SerBinario\SAD\Bundle\SADBundle\RN\VagaDisponivelRN
    rn.class.areaDesejadaRN: SerBinario\SAD\Bundle\SADBundle\RN\AreaDesejadaRN
    rn.class.funcaoRN: SerBinario\SAD\Bundle\SADBundle\RN\FuncaoRN
    rn.class.chamadaRN: SerBinario\SAD\Bundle\SADBundle\RN\ChamadaRN
    

services:
    empreendedor_dao:
        class:  %dao.class.empreendedor%
        arguments:  [ @doctrine.orm.entity_manager ]
        public: false
    empreendedor_rn:
        class:  %rn.class.empreendedor%
        arguments:  [ @empreendedor_dao ]
        
    candidato_dao:
        class:  %dao.class.candidato%
        arguments:  [ @doctrine.orm.entity_manager ]
        public: false
    candidato_rn:
        class:  %rn.class.candidato%
        arguments:  [ @candidato_dao ]
        
    autonomo_dao:
        class:  %dao.class.autonomo%
        arguments:  [ @doctrine.orm.entity_manager ]
        public: false 
    autonomo_rn:
        class:  %rn.class.autonomo%
        arguments:  [ @autonomo_dao ]
        
    empresa_dao:
        class:  %dao.class.empresa%
        arguments:  [ @doctrine.orm.entity_manager ]
        public: false 
    empresa_rn:
        class:  %rn.class.empresa%
        arguments:  [ @empresa_dao ]
        
    curso_dao:
        class:  %dao.class.curso%
        arguments:  [ @doctrine.orm.entity_manager ]
        public: false 
    curso_rn:
        class:  %rn.class.curso%
        arguments:  [ @curso_dao ]
    
    capacitacoes_dao:
        class:  %dao.class.capacitacoes%
        arguments:  [ @doctrine.orm.entity_manager ]
        public: false 
    capacitacoes_rn:
        class:  %rn.class.capacitacoes%
        arguments:  [ @capacitacoes_dao ]
        
    empresaCurso_dao:
        class:  %dao.class.empresaCurso%
        arguments:  [ @doctrine.orm.entity_manager ]
        public: false 
    empresaCurso_rn:
        class:  %rn.class.empresaCurso%
        arguments:  [ @empresaCurso_dao ]
        
    empresaCapacitacoes_dao:
        class:  %dao.class.empresaCapacitacoes%
        arguments:  [ @doctrine.orm.entity_manager ]
        public: false 
    empresaCapacitacoes_rn:
        class:  %rn.class.empresaCapacitacoes%
        arguments:  [ @empresaCapacitacoes_dao ]
    vagas_dao:
        class:  %dao.class.vagas%
        arguments:  [ @doctrine.orm.entity_manager ]
        public: false
    vagas_rn:
        class:  %rn.class.vagas%
        arguments:  [ @vagas_dao ]
    vagaDisponivel_dao:
        class:  %dao.class.vagaDisponivel%
        arguments:  [ @doctrine.orm.entity_manager ]
        public: false 
    vagaDisponivel_rn:
        class:  %rn.class.vagaDisponivel%
        arguments:  [ @vagaDisponivel_dao ]
    areaDesejada_dao:
        class:  %dao.class.AreaDesejadaDAO%
        arguments:  [ @doctrine.orm.entity_manager ]
        public: false 
    areaDesejada_rn:
        class:  %rn.class.areaDesejadaRN%
        arguments:  [ @areaDesejada_dao ]
    funcao_dao:
        class:  %dao.class.funcaoDAO%
        arguments:  [ @doctrine.orm.entity_manager ]
        public: false 
    funcao_rn:
        class:  %rn.class.funcaoRN%
        arguments:  [ @funcao_dao ]
    chamada_dao:
        class:  %dao.class.chamadaDAO%
        arguments:  [ @doctrine.orm.entity_manager ]
        public: false
    chamada_rn:
        class:  %rn.class.chamadaRN%
        arguments:  [ @chamada_dao ]
        